name: example
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.0.0"

dependencies:
  dart_odbc:
    path: ../
  dotenv: ^4.2.0
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

flutter:
  assets:
    - assets/test.xlsx
